/* ALVA Admin — Fases 3 a 5 + fundamentos 6/7 */
(() => {
  const ref = {companies:[],products:[],plans:[],subscriptions:[],profiles:[],invoices:[],payments:[],tickets:[],environments:[]};
  const money = (v,c='MXN') => new Intl.NumberFormat('es-MX',{style:'currency',currency:c||'MXN'}).format(Number(v||0));
  const dateOnly = v => v ? new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(`${String(v).slice(0,10)}T12:00:00`)) : '—';
  const isoDate = d => { const x=new Date(d); return x.toISOString().slice(0,10); };
  const today = () => isoDate(new Date());
  const plusDays = n => { const d=new Date(); d.setDate(d.getDate()+n); return isoDate(d); };
  const labelsMap={trial:'Prueba',active:'Activo',paused:'Pausado',cancelled:'Cancelado',expired:'Vencido',draft:'Borrador',pending:'Pendiente',paid:'Pagado',overdue:'Vencido',void:'Anulado',open:'Abierto',in_progress:'En proceso',waiting_customer:'Esperando cliente',resolved:'Resuelto',closed:'Cerrado',planned:'Planeado',inactive:'Inactivo',reserved:'Reservado'};
  const statusBadge = s => { const cls={active:'green',paid:'green',resolved:'green',closed:'green',trial:'amber',pending:'amber',planned:'amber',waiting_customer:'amber',paused:'amber',overdue:'red',cancelled:'red',expired:'red',void:'red'}[s]||''; return `<span class="badge ${cls}">${esc(labelsMap[s]||s||'—')}</span>`; };
  const priorityLabel = p => `<span class="priority ${esc(p)}">${esc({low:'Baja',normal:'Normal',high:'Alta',urgent:'Urgente'}[p]||p)}</span>`;

  function setupUI(){
    const subscriptions=$('#subscriptions');
    if(subscriptions) subscriptions.innerHTML=`<div class="section-card"><div class="section-toolbar"><div><span class="eyebrow">FASE 3 · CONTROL COMERCIAL</span><h2>Suscripciones / Licencias</h2><p>Relaciona cada empresa con el producto contratado, precio, vigencia, renovación y capacidad.</p></div><div class="toolbar-actions"><button id="new-plan" class="btn-secondary">+ Plan</button><button id="new-subscription" class="btn-primary">+ Suscripción</button></div></div><div id="subscription-summary" class="module-summary"></div><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Producto / plan</th><th>Precio</th><th>Vigencia</th><th>Estado</th><th></th></tr></thead><tbody id="subscriptions-table"></tbody></table></div><div id="plans-strip" class="plan-strip"></div></div>`;

    const billing=$('#billing');
    if(billing) billing.innerHTML=`<div class="section-card"><div class="section-toolbar"><div><span class="eyebrow">FASE 4 · FINANZAS</span><h2>Cobranza</h2><p>Cargos, vencimientos, pagos y situación de cuenta por cliente.</p></div><button id="new-invoice" class="btn-primary">+ Nuevo cargo</button></div><div id="billing-summary" class="module-summary"></div><div class="table-wrap"><table><thead><tr><th>Folio</th><th>Cliente / concepto</th><th>Vence</th><th>Total</th><th>Pagado</th><th>Estado</th><th></th></tr></thead><tbody id="invoices-table"></tbody></table></div><p class="table-note">Los folios son internos de ALVA; la integración fiscal/CFDI queda fuera de esta etapa.</p></div>`;

    const support=$('#support');
    if(support) support.innerHTML=`<div class="section-card"><div class="section-toolbar"><div><span class="eyebrow">FASE 5 · OPERACIÓN</span><h2>Soporte</h2><p>Incidencias asociadas a cliente, producto y suscripción, con prioridad e historial.</p></div><button id="new-ticket" class="btn-primary">+ Nuevo ticket</button></div><div id="support-summary" class="module-summary"></div><div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Cliente / asunto</th><th>Producto</th><th>Prioridad</th><th>Estado</th><th>Actualizado</th><th></th></tr></thead><tbody id="tickets-table"></tbody></table></div></div>`;

    const settings=$('#settings');
    if(settings) settings.innerHTML=`<div class="section-card"><span class="eyebrow">SISTEMA</span><h2>Configuración e infraestructura</h2><p>ALVA comparte Supabase con CyA Asesor Digital, manteniendo aislamiento lógico mediante tablas <code>alva_</code>, RLS y helpers privados.</p><div class="settings-grid"><div><span>Base de datos</span><strong>Supabase · us-east-1</strong></div><div><span>Autenticación</span><strong>Supabase Auth</strong></div><div><span>Seguridad</span><strong>RLS activo</strong></div><div><span>Estado</span><strong>Fases 2–5 operativas</strong></div></div><div class="dialog-section"><div class="section-toolbar"><div><span class="eyebrow">EXPANSIÓN MULTIPRODUCTO</span><h2>Entornos de productos</h2><p>Registro técnico para producción, staging y desarrollo de cada producto ALVA.</p></div><button id="new-environment" class="btn-secondary">+ Entorno</button></div><div id="environments-grid" class="environment-grid"></div></div><div id="portal-foundation" class="portal-foundation"><div><strong>Portal de cliente — fundamento preparado</strong><span>Las membresías existen, pero todavía no se expone información comercial a clientes.</span></div><span class="badge amber">Fase 6 segura</span></div></div>`;

    const dashboard=$('#dashboard .metric-grid');
    if(dashboard && !$('#ops-metrics')) dashboard.insertAdjacentHTML('afterend',`<div id="ops-metrics" class="ops-metric-grid"><article class="ops-metric"><span>Suscripciones activas</span><strong id="ops-active-subs">—</strong><small>Productos contratados</small></article><article class="ops-metric attention"><span>Renovaciones 30 días</span><strong id="ops-renewals">—</strong><small>Requieren seguimiento</small></article><article class="ops-metric"><span>Cobranza pendiente</span><strong id="ops-pending">—</strong><small>Saldo abierto</small></article><article class="ops-metric"><span>Tickets abiertos</span><strong id="ops-tickets">—</strong><small>Soporte por atender</small></article></div>`);

    document.body.insertAdjacentHTML('beforeend', dialogsHTML());
  }

  function dialogsHTML(){ return `
  <dialog id="plan-dialog" class="editor-dialog"><form id="plan-form"><div class="dialog-head"><div><span class="eyebrow">PLAN</span><h2 id="plan-title">Nuevo plan</h2></div><button type="button" class="icon-button" data-x="plan-dialog">×</button></div><input type="hidden" id="plan-id"><div class="form-grid"><label>Producto<select id="plan-product" required></select></label><label>Código<input id="plan-code" required></label><label>Nombre<input id="plan-name" required></label><label>Estado<select id="plan-status"><option value="active">Activo</option><option value="inactive">Inactivo</option><option value="reserved">Reservado</option></select></label><label>Periodicidad<select id="plan-frequency"><option value="monthly">Mensual</option><option value="quarterly">Trimestral</option><option value="semiannual">Semestral</option><option value="annual">Anual</option><option value="one_time">Pago único</option><option value="custom">Personalizada</option></select></label><label>Precio<input id="plan-price" type="number" min="0" step="0.01"></label><label>Usuarios incluidos<input id="plan-users" type="number" min="0"></label><label class="span-2">Descripción<textarea id="plan-description" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="btn-secondary" data-x="plan-dialog">Cancelar</button><button class="btn-primary">Guardar plan</button></div></form></dialog>

  <dialog id="subscription-dialog" class="editor-dialog"><form id="subscription-form"><div class="dialog-head"><div><span class="eyebrow">SUSCRIPCIÓN</span><h2 id="subscription-title">Nueva suscripción</h2></div><button type="button" class="icon-button" data-x="subscription-dialog">×</button></div><input type="hidden" id="subscription-id"><div class="form-grid"><label>Empresa<select id="subscription-company" required></select></label><label>Producto<select id="subscription-product" required></select></label><label>Plan<select id="subscription-plan"><option value="">Personalizado / sin plan</option></select></label><label>Estado<select id="subscription-status"><option value="trial">Prueba</option><option value="active" selected>Activo</option><option value="paused">Pausado</option><option value="cancelled">Cancelado</option><option value="expired">Vencido</option></select></label><label>Periodicidad<select id="subscription-frequency"><option value="monthly">Mensual</option><option value="quarterly">Trimestral</option><option value="semiannual">Semestral</option><option value="annual">Anual</option><option value="one_time">Pago único</option><option value="custom">Personalizada</option></select></label><label>Precio contratado<input id="subscription-price" type="number" min="0" step="0.01"></label><label>Límite de usuarios<input id="subscription-seats" type="number" min="0"></label><label>Fecha de inicio<input id="subscription-start" type="date" required></label><label>Próxima renovación<input id="subscription-renewal" type="date"></label><label>Fecha final<input id="subscription-end" type="date"></label><label>ID externo / tenant<input id="subscription-external"></label><label>URL de acceso<input id="subscription-url" type="url"></label><label class="span-2">Notas<textarea id="subscription-notes" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="btn-secondary" data-x="subscription-dialog">Cancelar</button><button class="btn-primary">Guardar suscripción</button></div></form></dialog>

  <dialog id="invoice-dialog" class="editor-dialog"><form id="invoice-form"><div class="dialog-head"><div><span class="eyebrow">COBRANZA</span><h2>Nuevo cargo</h2></div><button type="button" class="icon-button" data-x="invoice-dialog">×</button></div><div class="form-grid"><label>Empresa<select id="invoice-company" required></select></label><label>Suscripción<select id="invoice-subscription"><option value="">Sin suscripción</option></select></label><label>Producto<select id="invoice-product"><option value="">Sin producto</option></select></label><label>Estado<select id="invoice-status"><option value="pending">Pendiente</option><option value="draft">Borrador</option></select></label><label class="span-2">Concepto<input id="invoice-concept" required></label><label>Emisión<input id="invoice-issue" type="date" required></label><label>Vencimiento<input id="invoice-due" type="date"></label><label>Subtotal<input id="invoice-subtotal" type="number" min="0" step="0.01" value="0"></label><label>Impuestos<input id="invoice-tax" type="number" min="0" step="0.01" value="0"></label><label>Total<div id="invoice-total" class="readonly-box">$0.00</div></label><label class="span-2">Notas<textarea id="invoice-notes" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="btn-secondary" data-x="invoice-dialog">Cancelar</button><button class="btn-primary">Guardar cargo</button></div></form></dialog>

  <dialog id="payment-dialog" class="editor-dialog"><form id="payment-form"><div class="dialog-head"><div><span class="eyebrow">PAGO</span><h2>Registrar pago</h2></div><button type="button" class="icon-button" data-x="payment-dialog">×</button></div><input type="hidden" id="payment-invoice"><div class="form-grid"><label>Monto<input id="payment-amount" type="number" min="0.01" step="0.01" required></label><label>Fecha y hora<input id="payment-date" type="datetime-local" required></label><label>Método<input id="payment-method" placeholder="Transferencia, efectivo, tarjeta…"></label><label>Referencia<input id="payment-reference"></label><label class="span-2">Notas<textarea id="payment-notes" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="btn-secondary" data-x="payment-dialog">Cancelar</button><button class="btn-primary">Registrar pago</button></div></form></dialog>

  <dialog id="ticket-dialog" class="editor-dialog wide-dialog"><div class="dialog-head" style="padding:24px 24px 0"><div><span class="eyebrow">SOPORTE</span><h2 id="ticket-title">Nuevo ticket</h2></div><button type="button" class="icon-button" data-x="ticket-dialog">×</button></div><form id="ticket-form" style="padding:0 24px 24px"><input type="hidden" id="ticket-id"><div class="form-grid"><label>Empresa<select id="ticket-company" required></select></label><label>Producto<select id="ticket-product"><option value="">General</option></select></label><label>Suscripción<select id="ticket-subscription"><option value="">Sin suscripción</option></select></label><label>Asignado a<select id="ticket-assigned"><option value="">Sin asignar</option></select></label><label>Prioridad<select id="ticket-priority"><option value="low">Baja</option><option value="normal" selected>Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Estado<select id="ticket-status"><option value="open">Abierto</option><option value="in_progress">En proceso</option><option value="waiting_customer">Esperando cliente</option><option value="resolved">Resuelto</option><option value="closed">Cerrado</option></select></label><label class="span-2">Asunto<input id="ticket-subject" required></label><label class="span-2">Descripción<textarea id="ticket-description" rows="4" required></textarea></label><label>Solicitante<input id="ticket-requester"></label><label>Correo solicitante<input id="ticket-email" type="email"></label></div><div class="dialog-actions"><button type="button" class="btn-secondary" data-x="ticket-dialog">Cancelar</button><button class="btn-primary">Guardar ticket</button></div></form><section id="ticket-thread-section" class="dialog-section" style="padding:0 24px 24px" hidden><h3>Historial</h3><div id="ticket-thread" class="ticket-thread"></div><form id="message-form" class="message-composer"><textarea id="message-body" placeholder="Escribe una respuesta o nota…" required></textarea><button class="btn-primary">Agregar</button><label class="message-options"><input id="message-internal" type="checkbox"> Nota interna</label></form></section></dialog>

  <dialog id="environment-dialog" class="editor-dialog"><form id="environment-form"><div class="dialog-head"><div><span class="eyebrow">ENTORNO</span><h2>Entorno de producto</h2></div><button type="button" class="icon-button" data-x="environment-dialog">×</button></div><input type="hidden" id="environment-id"><div class="form-grid"><label>Producto<select id="environment-product" required></select></label><label>Entorno<select id="environment-name"><option value="production">Producción</option><option value="staging">Staging</option><option value="development">Desarrollo</option></select></label><label>Estado<select id="environment-status"><option value="active">Activo</option><option value="planned">Planeado</option><option value="inactive">Inactivo</option></select></label><label>Supabase project ref<input id="environment-supabase"></label><label class="span-2">URL aplicación<input id="environment-app" type="url"></label><label class="span-2">URL administración<input id="environment-admin" type="url"></label><label class="span-2">Repositorio<input id="environment-repo" type="url"></label><label class="span-2">Notas<textarea id="environment-notes" rows="3"></textarea></label></div><div class="dialog-actions"><button type="button" class="btn-secondary" data-x="environment-dialog">Cancelar</button><button class="btn-primary">Guardar entorno</button></div></form></dialog>`; }

  async function ensureRefs(force=false){
    if(!state.db||!state.user) return false;
    if(!force && ref.companies.length && ref.products.length) return true;
    const [c,p,pl,pr]=await Promise.all([
      state.db.from('alva_companies').select('id,trade_name,status').order('trade_name'),
      state.db.from('alva_products').select('id,code,name,status,currency').order('sort_order'),
      state.db.from('alva_product_plans').select('*').order('sort_order').order('name'),
      state.db.from('alva_profiles').select('id,display_name,full_name,is_active').eq('is_active',true).order('display_name')
    ]);
    ref.companies=c.data||[]; ref.products=p.data||[]; ref.plans=pl.data||[]; ref.profiles=pr.data||[];
    return true;
  }
  const optionHTML=(items,value,label,blank='')=>`${blank?`<option value="">${esc(blank)}</option>`:''}${items.map(x=>`<option value="${esc(x[value])}">${esc(label(x))}</option>`).join('')}`;
  function fillCoreSelects(){
    $('#subscription-company').innerHTML=optionHTML(ref.companies,'id',x=>x.trade_name);
    $('#subscription-product').innerHTML=optionHTML(ref.products,'id',x=>`${x.code} · ${x.name}`);
    $('#plan-product').innerHTML=optionHTML(ref.products,'id',x=>`${x.code} · ${x.name}`);
    $('#invoice-company').innerHTML=optionHTML(ref.companies,'id',x=>x.trade_name);
    $('#invoice-product').innerHTML=optionHTML(ref.products,'id',x=>`${x.code} · ${x.name}`,'Sin producto');
    $('#ticket-company').innerHTML=optionHTML(ref.companies,'id',x=>x.trade_name);
    $('#ticket-product').innerHTML=optionHTML(ref.products,'id',x=>`${x.code} · ${x.name}`,'General');
    $('#ticket-assigned').innerHTML=optionHTML(ref.profiles,'id',x=>x.display_name||x.full_name||'Usuario','Sin asignar');
    $('#environment-product').innerHTML=optionHTML(ref.products,'id',x=>`${x.code} · ${x.name}`);
  }
  function refreshPlanSelect(selected=''){
    const product=$('#subscription-product').value;
    const plans=ref.plans.filter(x=>x.product_id===product && x.status!=='inactive');
    $('#subscription-plan').innerHTML=optionHTML(plans,'id',x=>`${x.name}${x.price!=null?` · ${money(x.price,x.currency)}`:''}`,'Personalizado / sin plan');
    $('#subscription-plan').value=selected||'';
  }
  function refreshSubscriptionSelects(){
    const invoiceCompany=$('#invoice-company')?.value;
    const ticketCompany=$('#ticket-company')?.value;
    if($('#invoice-subscription')) $('#invoice-subscription').innerHTML=optionHTML(ref.subscriptions.filter(s=>!invoiceCompany||s.company_id===invoiceCompany),'id',s=>`${companyName(s.company_id)} · ${productName(s.product_id)}`,'Sin suscripción');
    if($('#ticket-subscription')) $('#ticket-subscription').innerHTML=optionHTML(ref.subscriptions.filter(s=>!ticketCompany||s.company_id===ticketCompany),'id',s=>`${productName(s.product_id)} · ${labelsMap[s.status]||s.status}`,'Sin suscripción');
  }
  const companyName=id=>ref.companies.find(x=>x.id===id)?.trade_name||'Empresa';
  const productName=id=>ref.products.find(x=>x.id===id)?.name||'Producto';
  const planName=id=>ref.plans.find(x=>x.id===id)?.name||'Personalizado';

  async function loadSubscriptions(){
    if(!await ensureRefs(true)) return;
    const {data,error}=await state.db.from('alva_subscriptions').select('*').order('updated_at',{ascending:false});
    if(error){toast('No se pudieron cargar las suscripciones.',true);return}
    ref.subscriptions=data||[]; fillCoreSelects(); refreshSubscriptionSelects();
    const active=ref.subscriptions.filter(s=>s.status==='active').length;
    const trials=ref.subscriptions.filter(s=>s.status==='trial').length;
    const soon=ref.subscriptions.filter(s=>s.renewal_date && s.renewal_date>=today() && s.renewal_date<=plusDays(30) && ['active','trial'].includes(s.status)).length;
    const mrr=ref.subscriptions.filter(s=>s.status==='active').reduce((sum,s)=>{const p=Number(s.contracted_price||0);return sum+(s.billing_frequency==='monthly'?p:s.billing_frequency==='quarterly'?p/3:s.billing_frequency==='semiannual'?p/6:s.billing_frequency==='annual'?p/12:0)},0);
    $('#subscription-summary').innerHTML=`<div class="summary-box"><span>Activas</span><strong>${active}</strong><small>Suscripciones operativas</small></div><div class="summary-box"><span>Renuevan en 30 días</span><strong>${soon}</strong><small>Seguimiento comercial</small></div><div class="summary-box"><span>MRR estimado</span><strong>${money(mrr)}</strong><small>${trials} en prueba</small></div>`;
    $('#subscriptions-table').innerHTML=ref.subscriptions.map(s=>`<tr><td><strong>${esc(companyName(s.company_id))}</strong><small>${dateOnly(s.start_date)}</small></td><td><strong>${esc(productName(s.product_id))}</strong><small>${esc(planName(s.plan_id))}</small></td><td><span class="money">${s.contracted_price==null?'—':money(s.contracted_price,s.currency)}</span><div class="sub-detail"><span>${esc(s.billing_frequency)}</span>${s.seat_limit!=null?`<span>${s.seat_limit} usuarios</span>`:''}</div></td><td><strong>${dateOnly(s.renewal_date)}</strong><small>${s.end_date?`Final ${dateOnly(s.end_date)}`:''}</small></td><td>${statusBadge(s.status)}</td><td><button class="row-button" data-edit-sub="${s.id}">Editar</button></td></tr>`).join('')||'<tr><td colspan="6">Sin suscripciones todavía.</td></tr>';
    $('#plans-strip').innerHTML=ref.plans.slice(0,9).map(p=>`<article class="plan-mini"><header><strong>${esc(p.name)}</strong>${statusBadge(p.status)}</header><p>${esc(productName(p.product_id))} · ${esc(p.description||'Plan comercial')}</p><footer><span>${p.price==null?'Precio por definir':money(p.price,p.currency)}</span><button class="row-button" data-edit-plan="${p.id}">Editar</button></footer></article>`).join('')||'<div class="empty-state">Aún no hay planes; puedes trabajar con suscripciones personalizadas.</div>';
    $$('[data-edit-sub]').forEach(b=>b.onclick=()=>openSubscription(b.dataset.editSub));
    $$('[data-edit-plan]').forEach(b=>b.onclick=()=>openPlan(b.dataset.editPlan));
  }

  async function openPlan(id=''){
    await ensureRefs(); fillCoreSelects(); const p=ref.plans.find(x=>x.id===id);
    $('#plan-title').textContent=p?'Editar plan':'Nuevo plan'; $('#plan-id').value=p?.id||''; $('#plan-product').value=p?.product_id||ref.products[0]?.id||''; $('#plan-product').disabled=!!p; $('#plan-code').value=p?.code||''; $('#plan-code').disabled=!!p; $('#plan-name').value=p?.name||''; $('#plan-status').value=p?.status||'active'; $('#plan-frequency').value=p?.billing_frequency||'monthly'; $('#plan-price').value=p?.price??''; $('#plan-users').value=p?.included_users??''; $('#plan-description').value=p?.description||''; $('#plan-dialog').showModal();
  }
  async function savePlan(e){ e.preventDefault(); const id=$('#plan-id').value; const payload={name:$('#plan-name').value.trim(),status:$('#plan-status').value,billing_frequency:$('#plan-frequency').value,price:$('#plan-price').value===''?null:Number($('#plan-price').value),included_users:$('#plan-users').value===''?null:Number($('#plan-users').value),description:$('#plan-description').value.trim()||null,updated_by:state.user.id}; let r;if(id)r=await state.db.from('alva_product_plans').update(payload).eq('id',id);else r=await state.db.from('alva_product_plans').insert({...payload,product_id:$('#plan-product').value,code:$('#plan-code').value.trim().toUpperCase(),sort_order:(ref.plans.length+1)*10,created_by:state.user.id}); if(r.error){toast('No se pudo guardar el plan.',true);return} $('#plan-dialog').close();toast('Plan guardado');await loadSubscriptions(); }

  async function openSubscription(id=''){
    await ensureRefs(true); const s=ref.subscriptions.find(x=>x.id===id); fillCoreSelects(); $('#subscription-id').value=s?.id||''; $('#subscription-title').textContent=s?'Editar suscripción':'Nueva suscripción'; $('#subscription-company').value=s?.company_id||ref.companies[0]?.id||''; $('#subscription-product').value=s?.product_id||ref.products.find(x=>x.status==='active')?.id||ref.products[0]?.id||''; refreshPlanSelect(s?.plan_id||''); $('#subscription-status').value=s?.status||'active'; $('#subscription-frequency').value=s?.billing_frequency||'monthly'; $('#subscription-price').value=s?.contracted_price??''; $('#subscription-seats').value=s?.seat_limit??''; $('#subscription-start').value=s?.start_date||today(); $('#subscription-renewal').value=s?.renewal_date||''; $('#subscription-end').value=s?.end_date||''; $('#subscription-external').value=s?.external_tenant_id||''; $('#subscription-url').value=s?.access_url||''; $('#subscription-notes').value=s?.notes||''; $('#subscription-dialog').showModal();
  }
  async function saveSubscription(e){ e.preventDefault(); const id=$('#subscription-id').value; const status=$('#subscription-status').value; const existing=ref.subscriptions.find(x=>x.id===id); const payload={company_id:$('#subscription-company').value,product_id:$('#subscription-product').value,plan_id:$('#subscription-plan').value||null,status,billing_frequency:$('#subscription-frequency').value,contracted_price:$('#subscription-price').value===''?null:Number($('#subscription-price').value),seat_limit:$('#subscription-seats').value===''?null:Number($('#subscription-seats').value),start_date:$('#subscription-start').value,renewal_date:$('#subscription-renewal').value||null,end_date:$('#subscription-end').value||null,cancelled_at:status==='cancelled'?(existing?.cancelled_at||new Date().toISOString()):null,external_tenant_id:$('#subscription-external').value.trim()||null,access_url:$('#subscription-url').value.trim()||null,notes:$('#subscription-notes').value.trim()||null,updated_by:state.user.id}; let r;if(id)r=await state.db.from('alva_subscriptions').update(payload).eq('id',id);else r=await state.db.from('alva_subscriptions').insert({...payload,created_by:state.user.id}); if(r.error){toast('No se pudo guardar la suscripción.',true);return} $('#subscription-dialog').close();toast('Suscripción guardada');await loadSubscriptions();await loadOpsDashboard(); }

  async function loadBilling(){
    await ensureRefs(true); await state.db.from('alva_invoices').update({status:'overdue',updated_by:state.user.id}).eq('status','pending').lt('due_date',today());
    const [i,p]=await Promise.all([state.db.from('alva_invoices').select('*').order('created_at',{ascending:false}),state.db.from('alva_payments').select('*').order('paid_at',{ascending:false})]);
    if(i.error||p.error){toast('No se pudo cargar la cobranza.',true);return} ref.invoices=i.data||[];ref.payments=p.data||[]; refreshSubscriptionSelects(); fillCoreSelects();
    const paidBy={};ref.payments.forEach(x=>paidBy[x.invoice_id]=(paidBy[x.invoice_id]||0)+Number(x.amount||0));
    const pending=ref.invoices.filter(x=>['pending','overdue'].includes(x.status)).reduce((a,x)=>a+Math.max(0,Number(x.total||0)-(paidBy[x.id]||0)),0);
    const overdue=ref.invoices.filter(x=>x.status==='overdue').reduce((a,x)=>a+Math.max(0,Number(x.total||0)-(paidBy[x.id]||0)),0);
    const month=new Date().toISOString().slice(0,7);const paidMonth=ref.payments.filter(x=>String(x.paid_at).slice(0,7)===month).reduce((a,x)=>a+Number(x.amount||0),0);
    $('#billing-summary').innerHTML=`<div class="summary-box"><span>Pendiente</span><strong>${money(pending)}</strong><small>Saldo abierto</small></div><div class="summary-box"><span>Vencido</span><strong>${money(overdue)}</strong><small>Requiere seguimiento</small></div><div class="summary-box"><span>Cobrado este mes</span><strong>${money(paidMonth)}</strong><small>Pagos registrados</small></div>`;
    $('#invoices-table').innerHTML=ref.invoices.map(x=>{const paid=paidBy[x.id]||0;return `<tr><td><strong>ALVA-${String(x.folio).padStart(6,'0')}</strong><small>${dateOnly(x.issue_date)}</small></td><td><strong>${esc(companyName(x.company_id))}</strong><small>${esc(x.concept)}</small></td><td>${dateOnly(x.due_date)}</td><td class="money">${money(x.total,x.currency)}</td><td class="money">${money(paid,x.currency)}</td><td>${statusBadge(x.status)}</td><td>${!['paid','cancelled','void'].includes(x.status)?`<button class="row-button" data-pay-invoice="${x.id}">Pago</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="7">Sin cargos registrados.</td></tr>';
    $$('[data-pay-invoice]').forEach(b=>b.onclick=()=>openPayment(b.dataset.payInvoice));
  }
  async function openInvoice(){ await ensureRefs(true); fillCoreSelects(); refreshSubscriptionSelects(); $('#invoice-issue').value=today(); $('#invoice-due').value=plusDays(7); $('#invoice-concept').value=''; $('#invoice-subtotal').value='0'; $('#invoice-tax').value='0'; $('#invoice-status').value='pending'; $('#invoice-notes').value='';updateInvoiceTotal();$('#invoice-dialog').showModal(); }
  const updateInvoiceTotal=()=>{const t=Number($('#invoice-subtotal')?.value||0)+Number($('#invoice-tax')?.value||0);if($('#invoice-total'))$('#invoice-total').textContent=money(t)};
  async function saveInvoice(e){ e.preventDefault(); const subtotal=Number($('#invoice-subtotal').value||0),tax=Number($('#invoice-tax').value||0); const sub=ref.subscriptions.find(x=>x.id===$('#invoice-subscription').value); const payload={company_id:$('#invoice-company').value,subscription_id:$('#invoice-subscription').value||null,product_id:$('#invoice-product').value||sub?.product_id||null,concept:$('#invoice-concept').value.trim(),issue_date:$('#invoice-issue').value,due_date:$('#invoice-due').value||null,status:$('#invoice-status').value,subtotal,tax,total:subtotal+tax,notes:$('#invoice-notes').value.trim()||null,created_by:state.user.id,updated_by:state.user.id}; const r=await state.db.from('alva_invoices').insert(payload); if(r.error){toast('No se pudo guardar el cargo.',true);return} $('#invoice-dialog').close();toast('Cargo registrado');await loadBilling();await loadOpsDashboard(); }
  async function openPayment(id){ const inv=ref.invoices.find(x=>x.id===id); const paid=ref.payments.filter(x=>x.invoice_id===id).reduce((a,x)=>a+Number(x.amount||0),0); $('#payment-invoice').value=id;$('#payment-amount').value=Math.max(0,Number(inv?.total||0)-paid).toFixed(2); const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('#payment-date').value=d.toISOString().slice(0,16);$('#payment-method').value='Transferencia';$('#payment-reference').value='';$('#payment-notes').value='';$('#payment-dialog').showModal(); }
  async function savePayment(e){e.preventDefault();const r=await state.db.from('alva_payments').insert({invoice_id:$('#payment-invoice').value,amount:Number($('#payment-amount').value),paid_at:new Date($('#payment-date').value).toISOString(),payment_method:$('#payment-method').value.trim()||null,reference:$('#payment-reference').value.trim()||null,notes:$('#payment-notes').value.trim()||null,created_by:state.user.id});if(r.error){toast('No se pudo registrar el pago.',true);return}$('#payment-dialog').close();toast('Pago registrado');await loadBilling();await loadOpsDashboard();}

  async function loadSupport(){
    await ensureRefs(true); const {data,error}=await state.db.from('alva_tickets').select('*').order('updated_at',{ascending:false}); if(error){toast('No se pudo cargar soporte.',true);return}ref.tickets=data||[];fillCoreSelects();refreshSubscriptionSelects(); const open=ref.tickets.filter(x=>!['resolved','closed'].includes(x.status)).length;const urgent=ref.tickets.filter(x=>x.priority==='urgent'&&!['resolved','closed'].includes(x.status)).length;const waiting=ref.tickets.filter(x=>x.status==='waiting_customer').length;$('#support-summary').innerHTML=`<div class="summary-box"><span>Abiertos</span><strong>${open}</strong><small>Por atender</small></div><div class="summary-box"><span>Urgentes</span><strong>${urgent}</strong><small>Prioridad inmediata</small></div><div class="summary-box"><span>Esperando cliente</span><strong>${waiting}</strong><small>Seguimiento pendiente</small></div>`;$('#tickets-table').innerHTML=ref.tickets.map(t=>`<tr><td><strong>#${String(t.ticket_number).padStart(5,'0')}</strong><small>${dateOnly(t.created_at)}</small></td><td class="ticket-subject"><strong>${esc(companyName(t.company_id))}</strong><small>${esc(t.subject)}</small></td><td>${esc(t.product_id?productName(t.product_id):'General')}</td><td>${priorityLabel(t.priority)}</td><td>${statusBadge(t.status)}</td><td>${fmtDate(t.updated_at)}</td><td><button class="row-button" data-edit-ticket="${t.id}">Abrir</button></td></tr>`).join('')||'<tr><td colspan="7">Sin tickets.</td></tr>';$$('[data-edit-ticket]').forEach(b=>b.onclick=()=>openTicket(b.dataset.editTicket));
  }
  async function openTicket(id=''){ await ensureRefs(true); const t=ref.tickets.find(x=>x.id===id);fillCoreSelects();refreshSubscriptionSelects();$('#ticket-id').value=t?.id||'';$('#ticket-title').textContent=t?`Ticket #${String(t.ticket_number).padStart(5,'0')}`:'Nuevo ticket';$('#ticket-company').value=t?.company_id||ref.companies[0]?.id||'';refreshSubscriptionSelects();$('#ticket-product').value=t?.product_id||'';$('#ticket-subscription').value=t?.subscription_id||'';$('#ticket-assigned').value=t?.assigned_to||state.user.id||'';$('#ticket-priority').value=t?.priority||'normal';$('#ticket-status').value=t?.status||'open';$('#ticket-subject').value=t?.subject||'';$('#ticket-description').value=t?.description||'';$('#ticket-requester').value=t?.requester_name||'';$('#ticket-email').value=t?.requester_email||'';$('#ticket-thread-section').hidden=!t;if(t)await loadMessages(t.id);$('#ticket-dialog').showModal(); }
  async function saveTicket(e){e.preventDefault();const id=$('#ticket-id').value;const old=ref.tickets.find(x=>x.id===id);const status=$('#ticket-status').value;const payload={company_id:$('#ticket-company').value,product_id:$('#ticket-product').value||null,subscription_id:$('#ticket-subscription').value||null,assigned_to:$('#ticket-assigned').value||null,priority:$('#ticket-priority').value,status,subject:$('#ticket-subject').value.trim(),description:$('#ticket-description').value.trim(),requester_name:$('#ticket-requester').value.trim()||null,requester_email:$('#ticket-email').value.trim()||null,resolved_at:status==='resolved'?(old?.resolved_at||new Date().toISOString()):(status==='closed'?old?.resolved_at:null),closed_at:status==='closed'?(old?.closed_at||new Date().toISOString()):null,updated_by:state.user.id};let r;if(id)r=await state.db.from('alva_tickets').update(payload).eq('id',id);else r=await state.db.from('alva_tickets').insert({...payload,created_by:state.user.id}).select().single();if(r.error){toast('No se pudo guardar el ticket.',true);return}toast('Ticket guardado');if(!id){$('#ticket-id').value=r.data.id;$('#ticket-thread-section').hidden=false}await loadSupport();await loadOpsDashboard();}
  async function loadMessages(ticketId){const {data}=await state.db.from('alva_ticket_messages').select('*').eq('ticket_id',ticketId).order('created_at');const items=data||[];$('#ticket-thread').innerHTML=items.map(m=>`<article class="ticket-message ${m.is_internal?'internal':''}"><header><strong>${m.author_user_id===state.user.id?'ALVA Admin':'Usuario'}${m.is_internal?' · Nota interna':''}</strong><time>${fmtDate(m.created_at)}</time></header><p>${esc(m.body)}</p></article>`).join('')||'<div class="empty-state">Sin mensajes todavía.</div>';}
  async function saveMessage(e){e.preventDefault();const id=$('#ticket-id').value;if(!id)return;const body=$('#message-body').value.trim();if(!body)return;const r=await state.db.from('alva_ticket_messages').insert({ticket_id:id,author_user_id:state.user.id,body,is_internal:$('#message-internal').checked});if(r.error){toast('No se pudo agregar el mensaje.',true);return}$('#message-body').value='';$('#message-internal').checked=false;await loadMessages(id);toast('Mensaje agregado');}

  async function loadSettingsPlus(){
    await ensureRefs(true); const [e,m]=await Promise.all([state.db.from('alva_product_environments').select('*').order('environment'),state.db.from('alva_portal_memberships').select('*',{count:'exact',head:true})]);ref.environments=e.data||[];fillCoreSelects();$('#environments-grid').innerHTML=ref.environments.map(x=>`<article class="environment-card"><header><h3>${esc(productName(x.product_id))} · ${esc(x.environment)}</h3>${statusBadge(x.status)}</header><dl><dt>Aplicación</dt><dd>${x.app_url?`<a href="${esc(x.app_url)}" target="_blank" rel="noopener">${esc(x.app_url)}</a>`:'—'}</dd><dt>Admin</dt><dd>${x.admin_url?`<a href="${esc(x.admin_url)}" target="_blank" rel="noopener">${esc(x.admin_url)}</a>`:'—'}</dd><dt>Repositorio</dt><dd>${x.repository_url?esc(x.repository_url):'—'}</dd></dl><div class="catalog-actions"><button class="row-button" data-edit-env="${x.id}">Editar</button></div></article>`).join('')||'<div class="empty-state">Aún no hay entornos registrados.</div>';$$('[data-edit-env]').forEach(b=>b.onclick=()=>openEnvironment(b.dataset.editEnv));const p=$('#portal-foundation');if(p)p.querySelector('span.badge').textContent=`${m.count||0} accesos · Fase 6 segura`;
  }
  async function openEnvironment(id=''){await ensureRefs();fillCoreSelects();const x=ref.environments.find(e=>e.id===id);$('#environment-id').value=x?.id||'';$('#environment-product').value=x?.product_id||ref.products[0]?.id||'';$('#environment-product').disabled=!!x;$('#environment-name').value=x?.environment||'production';$('#environment-name').disabled=!!x;$('#environment-status').value=x?.status||'active';$('#environment-app').value=x?.app_url||'';$('#environment-admin').value=x?.admin_url||'';$('#environment-repo').value=x?.repository_url||'';$('#environment-supabase').value=x?.supabase_project_ref||'';$('#environment-notes').value=x?.notes||'';$('#environment-dialog').showModal();}
  async function saveEnvironment(e){e.preventDefault();const id=$('#environment-id').value;const payload={status:$('#environment-status').value,app_url:$('#environment-app').value.trim()||null,admin_url:$('#environment-admin').value.trim()||null,repository_url:$('#environment-repo').value.trim()||null,supabase_project_ref:$('#environment-supabase').value.trim()||null,notes:$('#environment-notes').value.trim()||null};let r;if(id)r=await state.db.from('alva_product_environments').update(payload).eq('id',id);else r=await state.db.from('alva_product_environments').insert({...payload,product_id:$('#environment-product').value,environment:$('#environment-name').value});if(r.error){toast(r.error.message.includes('duplicate')?'Ese entorno ya existe para el producto.':'No se pudo guardar el entorno.',true);return}$('#environment-dialog').close();toast('Entorno guardado');await loadSettingsPlus();}

  async function loadOpsDashboard(){
    if(!state.db||!state.user)return;const [s,i,p,t]=await Promise.all([state.db.from('alva_subscriptions').select('status,renewal_date,contracted_price,billing_frequency'),state.db.from('alva_invoices').select('id,status,total,currency'),state.db.from('alva_payments').select('invoice_id,amount'),state.db.from('alva_tickets').select('status')]);if(s.error||i.error||p.error||t.error)return;const subs=s.data||[],invoices=i.data||[],payments=p.data||[],tickets=t.data||[];const paid={};payments.forEach(x=>paid[x.invoice_id]=(paid[x.invoice_id]||0)+Number(x.amount||0));const pending=invoices.filter(x=>['pending','overdue'].includes(x.status)).reduce((a,x)=>a+Math.max(0,Number(x.total||0)-(paid[x.id]||0)),0);const renewals=subs.filter(x=>x.renewal_date&&x.renewal_date>=today()&&x.renewal_date<=plusDays(30)&&['active','trial'].includes(x.status)).length;$('#ops-active-subs').textContent=subs.filter(x=>x.status==='active').length;$('#ops-renewals').textContent=renewals;$('#ops-pending').textContent=money(pending);$('#ops-tickets').textContent=tickets.filter(x=>!['resolved','closed'].includes(x.status)).length;
  }

  function bind(){
    $('#new-plan')?.addEventListener('click',()=>openPlan());$('#new-subscription')?.addEventListener('click',()=>openSubscription());$('#new-invoice')?.addEventListener('click',openInvoice);$('#new-ticket')?.addEventListener('click',()=>openTicket());$('#new-environment')?.addEventListener('click',()=>openEnvironment());
    $('#plan-form')?.addEventListener('submit',savePlan);$('#subscription-form')?.addEventListener('submit',saveSubscription);$('#invoice-form')?.addEventListener('submit',saveInvoice);$('#payment-form')?.addEventListener('submit',savePayment);$('#ticket-form')?.addEventListener('submit',saveTicket);$('#message-form')?.addEventListener('submit',saveMessage);$('#environment-form')?.addEventListener('submit',saveEnvironment);
    $$('[data-x]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.x)?.close()));
    $('#subscription-product')?.addEventListener('change',()=>refreshPlanSelect());$('#subscription-plan')?.addEventListener('change',()=>{const p=ref.plans.find(x=>x.id===$('#subscription-plan').value);if(p){$('#subscription-price').value=p.price??'';$('#subscription-frequency').value=p.billing_frequency||'monthly';$('#subscription-seats').value=p.included_users??''}});
    $('#invoice-company')?.addEventListener('change',refreshSubscriptionSelects);$('#ticket-company')?.addEventListener('change',refreshSubscriptionSelects);$('#invoice-subtotal')?.addEventListener('input',updateInvoiceTotal);$('#invoice-tax')?.addEventListener('input',updateInvoiceTotal);
  }

  setupUI();bind();
  const baseOpenView=openView; openView=async function(id,push=true){await baseOpenView(id,push);if(id==='subscriptions')await loadSubscriptions();if(id==='billing')await loadBilling();if(id==='support')await loadSupport();if(id==='settings')await loadSettingsPlus();};
  const baseLoadDashboard=loadDashboard; loadDashboard=async function(){await baseLoadDashboard();await loadOpsDashboard();};
  if(state?.user){loadOpsDashboard();const id=location.hash.replace('#','');if(id==='subscriptions')loadSubscriptions();if(id==='billing')loadBilling();if(id==='support')loadSupport();if(id==='settings')loadSettingsPlus();}
})();
