-- ALVA Soluciones Digitales — Fase 2
--
-- Este archivo fue el borrador original para un proyecto Supabase independiente.
-- NO debe ejecutarse en la arquitectura actual compartida con CyA Asesor Digital,
-- porque utilizaba nombres genéricos de tablas.
--
-- La implementación real fue aplicada directamente en Supabase mediante las
-- migraciones registradas:
--   20260916080820  alva_phase2_shared_core
--   alva_phase2_security_hardening
--   alva_phase2_performance_tuning
--
-- Todas las tablas públicas de ALVA usan el prefijo `alva_` y los helpers
-- sensibles se alojan en el esquema privado `alva_private`.
--
-- Ver docs/PHASE2.md para la arquitectura vigente.
